# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - prelistweb(deploy-test)

on:
    push:
        branches:
            - deploy-test
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Main install, build and test
              uses: ./.github/workflows/main

            - name: "Deploy to Azure Web App"
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v2
              with:
                  app-name: "prelistweb"
                  slot-name: "deploy-test"
                  publish-profile: ${{ secrets.AzureAppService_PublishProfile_5ab87ea37ca0401a8bd6e8c421e93af2 }}
                  package: .